### ISSUE TITLE
External node files are not created on XProc

### ISSUE THREAD

**Issue by AirQuick** [xspec/xspec#102] opened 2017-03-09 10:39 UTC
### In short

[`result-document()` in `test:report-value()`](https://github.com/xspec/xspec/blob/f4811a5976c637210e651f5b46d962f38d183f9b/src/compiler/generate-tests-utils.xsl#L579) does not work on XProc.

### Steps to repro

Clone [the last known good master](https://github.com/xspec/xspec/tree/f4811a5976c637210e651f5b46d962f38d183f9b).

Modify `test/xspec-result-naming-collision.xspec` to make its scenarios fail. For example, rewrite

```xml
    <x:expect>...</x:expect>
```

to

```xml
    <x:expect test="false()" />
```

Then run this command:

```winbatch
java -cp C:\xmlcalabash\xmlcalabash-1.1.15-97.jar com.xmlcalabash.drivers.Main ^
      -i source=test/xspec-result-naming-collision.xspec ^
      xspec-home=file:///C:/xspec/ ^
      -o result=test/xspec-result-naming-collision.html ^
      src\harnesses\saxon\saxon-xslt-harness.xproc
```
(It's essentially the same as [Wiki](https://github.com/xspec/xspec/wiki/Running-with-XProc/2d772f1cb64053cd88aa42ae851fdadce10f212c). The only important part is that `source` is `test/xspec-result-naming-collision.xspec`.)

The result HTML file `test/xspec-result-naming-collision.html` is created. It has these lines:

```html
                     <p><a href="d32.xml">d32.xml</a></p>
...
                     <p><a href="d41.xml">d41.xml</a></p>
```

But those `.xml` files are not created.

**Comment by AirQuick** [comment] 2017-03-09 10:42
Probably related: https://www.oxygenxml.com/forum/topic10208.html

**Comment by AirQuick** [comment] 2017-03-15 18:44
Same on [the current master](https://github.com/xspec/xspec/tree/74312e1100d7f289a5f70947e96cbdcdc8f1cc22) adapting the command line from [the updated Wiki](https://github.com/xspec/xspec/wiki/Running-with-XProc/79f398d6abe0194c32cc8ad5f18a55188129de27).

**Comment by cirulls** [comment] 2017-04-11 08:04
I have not tried to reproduce it yet but I had a quick look at the message in the Oxygen Forum and the related links. It seems to be related to an XProc bug or a different interpretation of the XProc specs. @AirQuick : Do you think we should investigate this further in XSpec?

**Comment by AirQuick** [comment] 2017-04-11 14:32
This issue seems to be an XProc harness bug or its design limitation at least.
I guess ideally the harness should cooperate with the compiler and save the documents to appropriate files.

I happened to find this issue while doing other things. So I filed it just for the record.
I personally do not need this feature, so for my part, it's ok to classify the issue as "deferred" or even "won't fix".

**Comment by cirulls** [comment] 2017-04-12 18:38
Thanks for your feedback. I'll classify it as won't fix and close it for now. If this comes back from an XSpec user, the bug is fixed in XProc or the XProc specifications change we can re-open it and re-visit the decision.

**Closed** 2017-04-12 18:38 UTC
Labels: wontfix
