### ISSUE TITLE
Dead URL reference in x:context/@href produces unclear error message

### ISSUE THREAD

**Issue by Crispness** [xspec/xspec#400] opened 2018-10-12 10:47 UTC
When referencing a non existent or unresponsive url in the href attribute of an x:context element, the error message produced says "XML document structures must start and end within the same entity."

This doesn't really explain to the user what the real problem is, i.e. that the document was not available to be processed. 

Can it be clarified?

Example xspec attached.

Note: GitHub does not allow upload of .xspec files so this was renamed by adding .txt on the end
[intro.xspec.txt](https://github.com/xspec/xspec/files/2472726/intro.xspec.txt)

**Comment by AirQuick** [comment] 2018-10-12 12:59
As for the runtime error, it is true that `XML document structures must start and end within the same entity` doesn't help. To diagnose, you need to see the log:

#### If you are using oXygen transformation scenario
The `ANT [XSpec for XSLT]` pane opens automatically on failure. There you can see what the actual error is:
```
     [java]   FODC0002: I/O error reported by XML parser processing
     [java]   http://xmldb.portinfo.co.uk/xml/4xv/000001.xml
```

#### If you are using oXygen XSpec Help plugin
See xspec/oXygen-XML-editor-xspec-support#24

**Comment by vincentml** [comment] 2018-10-14 00:32
I've made a change to output messages if URIs referenced in `stylesheet` or `href`` attributes are not available in XSLT tests. With this change, XSpec will produce a report that contains a message about the URI that is not available, instead of stopping with a cryptic message. For example:

```
Document referenced by context/@href is not available: does-not-exist.xml
Document referenced by expect/@href is not available: does-not-exist.xml 
Document referenced by param/@href is not available: does-not-exist.xml
The stylesheet referenced by x:description/@stylesheet is not available: does-not-exist.xsl
```

This change is in branch issue/400. @cirulls and @AirQuick please take a look. If this change looks okay I'll try to continue adding these messages for XQuery and Schematron tests.

A possible problem I noticed while working on this is that the messages are not included in the JUnit report. I'm not sure if I missed something or if this is an expected behavior or an existing problem with the JUnit report output.

**Comment by AirQuick** [comment] 2018-10-14 02:14
A few random quick thoughts:
* `mode="test:generate-variable-declarations"` checks `doc-available()` at compile time, but the URL available at compile time may not always available at runtime, particularly when it involves external web services. The check should be done in the same session as `doc()`.
* Injecting a dummy document in `mode="test:generate-variable-declarations"` could be a bad idea. One may write `@href="URL"` together with `@select="if (//text()[contains(., 'available')]) then 'foo' else 'bar'"` for example. Such expression will continue working quietly in an unexpected way even when URL go dead.
* As for JUnit report, it might be related to #330 or a number of issues written there.

**Comment by AirQuick** [comment] 2018-10-14 04:40
Also, just hiding `doc()` error is not always more helpful. It could even complicate the problem.
For example, the current master tells what's wrong with `<x:context href="https://httpbin.org/" />`:

```
Scenario for testing broken document
Error on line 29 column 3 of https://httpbin.org/:
  SXXP0003: Error reported by XML parser: The element type "link" must be terminated by the
  matching end-tag "</link>".
```

```
Scenario for testing broken document
Error at char 4 in xsl:variable/@select on line 43 column 69 of test.xsl:
  FODC0002: I/O error reported by XML parser processing https://httpbin.org/gzip: Invalid
  byte 1 of 1-byte UTF-8 sequence.
```

The proposed branch does not show these diagnoses.

**Comment by vincentml** [comment] 2018-10-14 05:14
Thanks for the quick feedback @AirQuick !

1. I've made a change to check doc-available at runtime.
2. I removed the generated text in `test:generate-variable-declarations`. However, now the report does not show if a fail or a message if the document is not available. I think the HTML report can still show a fail and a message if the URI is not available, but my first attempt did not work. 
3. I'll not worry about the JUnit for now.
4. This could probably be improved with `<xsl:try>` but that would require XSLT 3.0

**Comment by AirQuick** [comment] 2018-10-14 05:46
I'm afraid even `<document/>` could be harmful in `test:generate-variable-declarations`.

```xml
	<x:scenario label="Scenario">
		<x:call function="exactly-one">
			<x:param><slide><bogus>Wake up to WonderWidgets!</bogus></slide></x:param>
		</x:call>
		<x:expect href="https://httpbin.org/xml" label="Correct URL" select="slideshow/slide[1]/title" test="slide/title" />
		<x:expect href="https://httpbin.org/xm1" label="Wrong URL"   select="slideshow/slide[1]/title" test="slide/title" />
	</x:scenario>
```

This scenario terminates on the current master, but the proposed branch returns Success for the 2nd `x:expect`, because the dummy document turns the expectation into an empty sequence.

**Comment by vincentml** [comment] 2018-10-14 14:43
Thanks @AirQuick 

It seems better to keep the current behavior in which the test terminates if a referenced URI is not available. As you described, the system generated error messages are sometimes helpful, and producing a report might result in false-positives.

I've made a change in branch issue/400 to restore the original behavior to terminate if a referenced URI is not available. URIs referenced in `href` and `stylesheet` attributes are checked at compile time and a clear error message is output to the console if a URI is not available, in addition to any error messages that might be system generated.

**Comment by vincentml** [comment] 2018-10-14 22:29
I've added a similar check for XQuery tests to output a message to console if the query referenced by the `query-at` attribute is not available at compile time.

`The query referenced by description/@query-at is not available: does-not-exist.xq`

For Schematron tests, the Schematron compilation process already outputs a clear message if the Schematron referenced by the `schematron` attribute is not available.

`Source file C:\Users\vincent\Projects\xspec\xspec\test\unavailable\does-not-exist.sch does not exist`

**Comment by AirQuick** [comment] 2018-10-15 14:39
@vincentml 
Looks good to me in general. Some details could be improved, but that should be done in a pull request.
A few things to note:
* You may be already aware of it, but I submitted some pull requests to change the Bats test files for Windows. (#284, #285, #286)
* Not sure what you mean by "predictable" in 942d7baec314329764426560d325ba5c46d1e409, but it might possibly be related to #185.

**Comment by AirQuick** [comment] 2019-09-08 07:00
I verified that on Oxygen 21.1 build 2019071807, the following statement is still true

> #### If you are using oXygen transformation scenario
> The `ANT [XSpec for XSLT]` pane opens automatically on failure. There you can see what the actual error is:
> ```
>      [java]   FODC0002: I/O error reported by XML parser processing
>      [java]   http://xmldb.portinfo.co.uk/xml/4xv/000001.xml
> ```

and with XSpec Helper view 1.2.1, the following issue is mitigated (i.e. the `ANT [XSpec for XSLT]` pane opens automatically on failure and you can see the same error as above)

> #### If you are using oXygen XSpec Helper plugin
> See xspec/oXygen-XML-editor-xspec-support#24

So I'm closing this issue. Please feel free to reopen, if you don't see the actual error in the same environment.

**Closed by AirQuick** 2019-09-08 07:00 UTC
Labels: feature request
